name 'redis_cli'
maintainer 'fernandoaleman'
maintainer_email 'fernandoaleman@mac.com'
license 'Apache-2.0'
description 'Installs and configures redis_cli command'
version '0.1.0'
chef_version '>= 16'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'freebsd'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'
supports 'arch'
